### ISSUE TITLE
Line breaks in usage

### ISSUE THREAD

**Issue by ajm188** [ribozz/sphinx-argparse#38]
My generated usage text is way too long, so it generates a very narrow scrolling window in order view it all.

It would be awesome if there was a way to insert line breaks in the usage to make it look prettier.

**Comment by ajm188** [comment]
Based on my skimming, this relates most closely to #19

**Comment by dpryan79** [comment]
Are you referring specifically to "usage" lines, such as this: https://github.com/fidelram/deepTools/blob/master/deeptools/computeMatrix.py#L61-L62 ?

At least in cases such as that with html output you can insert `\n` where ever you like. Regarding the documentation for the actual options, I agree that it'd be nice to choose between scrolling down and sideways.

**Comment by ajm188** [comment]
@dpryan79 I'm talking more about the scrolling, I think. See my comments [here](https://github.com/Yelp/undebt/issues/39#issuecomment-243609724) for more info.

Happy to help dig in to this. Thanks for the reply!

**Comment by dpryan79** [comment]
This was annoying me too but the solution has nothing to do with sphinx-argparse. You end up needing to override the CSS style sheet that's applied. There are some nice step-by-step instructions [here](http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html). I'll add a link to that in the documentation, since I expect many people would like to change this.

**Comment by dpryan79** [comment]
This is now documented in the `develop` branch.

**Comment by ajm188** [comment]
Awesome thanks! @dpryan79++ 😄
