### ISSUE TITLE
Long positional arguments render incorrectly

### ISSUE THREAD

**Issue by selimt** [ribozz/sphinx-argparse#94]
If the name of a positional argument is long, the table gets rendered incorrectly:

![sphinx_argparse_pos](https://user-images.githubusercontent.com/15021762/38959807-f2cd4336-4316-11e8-8280-005d54981756.png)

Using sphinx-argparse 0.2.2 with Sphinx 1.7.2 on Python 2.7.5

**Comment by selimt** [comment]
Fixed it by adding a "docutils.conf" file with the following content:

```
[writers]
option_limit=0
```

**Comment by joaoe** [comment]
I had this issue before and investigated a bit.

`argparse` does output the option list correctly and consistently, so this is not a problem with `argparse`. The option list is output by `print_action_groups` in `ext.py`.

The problem is `docutil`, which converts the option lists to html. So, it seems adding a `docutil.conf` is a way to do it. https://bitbucket.org/birkenfeld/sphinx/commits/e34ebe4ff5a52a966c9e4da4872e5310173c27ae 

Btw, the correct syntax is (use dash, and value of 0 is ignored)
```
[writers]
option-limit=1
```

**Comment by dpryan79** [comment]
I've added this to the documentation, thanks!
